### ISSUE TITLE
小白ICP认证之Requirement

### ISSUE THREAD

**Issue by kavonm** [kavonm/icp-certification#6]
@maohuaming icp requirement issue

**Comment by maohuaming** [comment]
@kavonm 已经打上ICP标签，请申请开发。

**Comment by kavonm** [comment]
@maohuaming 申请开发 size: 1 Deadline: 2018-03-06

**Comment by maohuaming** [comment]
@kavonm 已指定assignee。

**Comment by maohuaming** [comment]
@kavonm 已打上size和in Progress标签。
